/**:
  ros__parameters:
    # Lidar settings
    use_lidar: false
    # QoS settings
    #input_qos: "SENSOR_DATA"
    input_qos: "SYSTEM_DEFAULT"
    # Map clearing settings
    map_clearing_frame_id: "camera_link"
    # Rviz visualization
    slice_visualization_attachment_frame_id: "camera_link"
    integrate_depth_rate_hz: 35.0  # >30.0

    static_mapper:
      esdf_slice_height: 0.0
      esdf_slice_min_height: -0.1
      esdf_slice_max_height: 1.0

    dynamic_mapper:
      esdf_slice_height: 0.0
      esdf_slice_min_height: -0.1
      esdf_slice_max_height: 1.0
